---
- name: Call childplaybooks for tomcat
  hosts: webserver
  tasks:
    - name: Call all chold playbooks
      include: "{{item}}"
      with_items:
        - install_tomcat.yml
        - copy_tomcatusers.yml
        - change_port.yml
        - restart_tomcat.yml
        - pause.yml 
        - check_tomcat_response.yml
