---
- name: Create user on all managed nodes
  hosts: all
  serial: 1
  tasks:
    - name: Create user
      user:
        name: Radha
        password: intelliqit
        uid: 2222
        home: /tmp/Radha
        shell: /bin/bash
        comment: "A super user"

...
